In [2]:
import pandas as pd
print(pd.__version__)

2.3.3

In [3]:
import pandas as pd

df = pd.read_csv("Data_LIC(Sheet1) (2).csv")

In [3]:
df.head()

,Number,Name,Age,Premium Amount,Policy Type,Mobile number,Gender,DOB,Premium Type,Date_of_Commencemnet,End_of_Premium_Paying,Date_of_Maturity
0,147178186,Roshan Lal,73,1500000,856,9.805566e+09,M,7/1/1953,Single,28/8/2021,28/8/2021,28/8/2031
1,147178189,Roshan Lal,73,1100000,858,9.805566e+09,M,7/1/1953,Single,28/8/2021,28/8/2021,28/8/2032
2,147171964,Sarwan Kumar Sharma,65,1500000,856,9.816606e+09,M,1/1/1961,Single,1/3/2021,1/3/2021,1/3/2031
3,145419621,Manora Dhadwal,79,1476064,856,7.018122e+09,F,22/9/1946,Single,28/12/2020,28/12/2020,28/12/2030
4,155065239,Shaym Kali,55,3669,75,9.625139e+09,F,1/7/1970,Half Year,28/11/2013,28/11/2033,28/11/2033

In [4]:
df.isnull().sum()

Number                   0
Name                     0
Age                      0
Premium Amount           0
Policy Type              0
Mobile number            3
Gender                   0
DOB                      0
Premium Type             0
Date_of_Commencemnet     0
End_of_Premium_Paying    0
Date_of_Maturity         0
dtype: int64

In [5]:
print(df.columns)

Index(['Number', 'Name ', 'Age ', 'Premium Amount', 'Policy Type ',
       'Mobile number', 'Gender', 'DOB', 'Premium Type ',
       'Date_of_Commencemnet ', 'End_of_Premium_Paying', 'Date_of_Maturity'],
      dtype='object')

In [4]:
df.head()

,Number,Name,Age,Premium Amount,Policy Type,Mobile number,Gender,DOB,Premium Type,Date_of_Commencemnet,End_of_Premium_Paying,Date_of_Maturity
0,147178186,Roshan Lal,73,1500000,856,9.805566e+09,M,7/1/1953,Single,28/8/2021,28/8/2021,28/8/2031
1,147178189,Roshan Lal,73,1100000,858,9.805566e+09,M,7/1/1953,Single,28/8/2021,28/8/2021,28/8/2032
2,147171964,Sarwan Kumar Sharma,65,1500000,856,9.816606e+09,M,1/1/1961,Single,1/3/2021,1/3/2021,1/3/2031
3,145419621,Manora Dhadwal,79,1476064,856,7.018122e+09,F,22/9/1946,Single,28/12/2020,28/12/2020,28/12/2030
4,155065239,Shaym Kali,55,3669,75,9.625139e+09,F,1/7/1970,Half Year,28/11/2013,28/11/2033,28/11/2033

In [5]:
df.shape

(135, 12)

In [6]:
df.isnull().sum()

Number                   0
Name                     0
Age                      0
Premium Amount           0
Policy Type              0
Mobile number            3
Gender                   0
DOB                      0
Premium Type             0
Date_of_Commencemnet     0
End_of_Premium_Paying    0
Date_of_Maturity         0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Number                 135 non-null    int64
 1   Name                   135 non-null    object
 2   Age                    135 non-null    int64
 3   Premium Amount         135 non-null    int64
 4   Policy Type            135 non-null    int64
 5   Mobile number          132 non-null    float64
 6   Gender                 135 non-null    object
 7   DOB                    135 non-null    object
 8   Premium Type           135 non-null    object
 9   Date_of_Commencemnet   135 non-null    object
 10  End_of_Premium_Paying  135 non-null    object
 11  Date_of_Maturity       135 non-null    object
dtypes: float64(1), int64(4), object(7)
memory usage: 12.8+ KB

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.describe()

             Number        Age   Premium Amount  Policy Type   Mobile number
count  1.350000e+02  135.000000    1.350000e+02    135.000000   1.320000e+02
mean   1.560608e+08   45.955556    9.216993e+04    552.807407   1.239484e+10
std    2.560160e+07   16.679537    2.631699e+05    364.018646   1.700308e+10
min    1.022234e+08    1.000000    1.860000e+02     75.000000   7.018122e+09
25%    1.523614e+08   34.000000    1.342000e+03    162.000000   8.580981e+09
50%    1.546806e+08   48.000000    8.776000e+03    814.000000   9.418034e+09
75%    1.552349e+08   58.000000    4.742100e+04    862.500000   9.816579e+09
max    4.171782e+08   84.000000    1.500000e+06    945.000000   9.818338e+10

In [10]:
df["Mobile number"] = df["Mobile number"].fillna("Not Available")

In [11]:
df.isnull().sum()

Number                   0
Name                     0
Age                      0
Premium Amount           0
Policy Type              0
Mobile number            0
Gender                   0
DOB                      0
Premium Type             0
Date_of_Commencemnet     0
End_of_Premium_Paying    0
Date_of_Maturity         0
dtype: int64

In [12]:
df["DOB"].head()

0     7/1/1953
1     7/1/1953
2     1/1/1961
3    22/9/1946
4     1/7/1970
Name: DOB, dtype: object

In [14]:
df["Date_of_Commencemnet"].head()

KeyError: 'Date_of_Commencemnet'

In [15]:
print(df.columns.tolist())

['Number', 'Name ', 'Age ', 'Premium Amount', 'Policy Type ', 'Mobile number', 'Gender', 'DOB', 'Premium Type ', 'Date_of_Commencemnet ', 'End_of_Premium_Paying', 'Date_of_Maturity']

In [16]:
df.columns = df.columns.str.strip()

In [17]:
print(df.columns.tolist())

['Number', 'Name', 'Age', 'Premium Amount', 'Policy Type', 'Mobile number', 'Gender', 'DOB', 'Premium Type', 'Date_of_Commencemnet', 'End_of_Premium_Paying', 'Date_of_Maturity']

In [18]:
df.rename(columns={
    "Number": "Policy_Number",
    "Name": "Name",
    "Age": "Age",
    "Premium Amount": "Premium_Amount",
    "Policy Type": "Policy_Type",
    "Mobile number": "Mobile_Number",
    "Gender": "Gender",
    "DOB": "DOB",
    "Premium Type": "Premium_Type",
    "Date_of_Commencemnet": "Date_of_Commencement",
    "End_of_Premium_Paying": "End_of_Premium_Paying",
    "Date_of_Maturity": "Date_of_Maturity"
}, inplace=True)

In [19]:
print(df.columns.tolist())

['Policy_Number', 'Name', 'Age', 'Premium_Amount', 'Policy_Type', 'Mobile_Number', 'Gender', 'DOB', 'Premium_Type', 'Date_of_Commencement', 'End_of_Premium_Paying', 'Date_of_Maturity']

In [20]:
df["DOB"] = pd.to_datetime(df["DOB"], dayfirst=True)

df["Date_of_Commencement"] = pd.to_datetime(
    df["Date_of_Commencement"], dayfirst=True
)

df["End_of_Premium_Paying"] = pd.to_datetime(
    df["End_of_Premium_Paying"], dayfirst=True
)

df["Date_of_Maturity"] = pd.to_datetime(
    df["Date_of_Maturity"], dayfirst=True
)

ValueError: unconverted data remains when parsing with format "%d/%m/%Y": "4", at position 61. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [21]:
df["Date_of_Commencement"].head(20)

0      28/8/2021
1      28/8/2021
2       1/3/2021
3     28/12/2020
4     28/11/2013
5     28/11/2008
6     14/11/2014
7      14/9/2022
8      12/6/2014
9      15/6/2017
10     22/6/2017
11     23/6/2014
12     16/2/2023
13      5/1/2023
14      7/2/2019
15     27/3/2021
16     28/3/2018
17     28/9/2012
18    20/11/2012
19    27/12/2013
Name: Date_of_Commencement, dtype: object

In [24]:
df["Date_of_Commencement"].iloc[55:70]

55    28/11/2003
56      7/3/2022
57      7/3/2022
58     11/3/2013
59    28/12/2019
60     28/3/2023
61    11/2/20144
62     11/2/2014
63      4/5/2016
64    26/12/2001
65     25/2/2021
66     25/2/2021
67     28/3/2026
68    14/12/2022
69     28/3/2018
Name: Date_of_Commencement, dtype: object

In [25]:

print(df.loc[61, "Date_of_Commencement"])

11/2/20144

In [26]:
df.loc[61, "Date_of_Commencement"] = "11/2/2014"

In [27]:
print(df.loc[61, "Date_of_Commencement"])

11/2/2014

In [29]:
clean_df = df.copy()

In [30]:
date_columns = [
    "DOB",
    "Date_of_Commencement",
    "End_of_Premium_Paying",
    "Date_of_Maturity"
]

for col in date_columns:
    clean_df[col] = pd.to_datetime(
        clean_df[col],
        dayfirst=True,
        errors="coerce"
    )

In [31]:
for col in date_columns:
    print(f"\nInvalid dates in {col}:")
    print(clean_df[clean_df[col].isna()][["Policy_Number", col]])

Invalid dates in DOB:
Empty DataFrame
Columns: [Policy_Number, DOB]
Index: []

Invalid dates in Date_of_Commencement:
Empty DataFrame
Columns: [Policy_Number, Date_of_Commencement]
Index: []

Invalid dates in End_of_Premium_Paying:
Empty DataFrame
Columns: [Policy_Number, End_of_Premium_Paying]
Index: []

Invalid dates in Date_of_Maturity:
    Policy_Number Date_of_Maturity
41      119816150              NaT
70      154757508              NaT

In [32]:
df.loc[[41, 70], [
    "Policy_Number",
    "Date_of_Maturity"
]]

    Policy_Number Date_of_Maturity
41      119816150          7/2/028
70      154757508         28//2042

In [33]:
clean_df.loc[
    clean_df["Policy_Number"] == 119816150,
    "Date_of_Maturity"
] = "07/02/2028"

In [37]:
clean_df.loc[
    clean_df["Policy_Number"] == 154757508,
    "Date_of_Maturity"
] = "28/03/2042"

In [38]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Policy_Number          135 non-null    int64
 1   Name                   135 non-null    object
 2   Age                    135 non-null    int64
 3   Premium_Amount         135 non-null    int64
 4   Policy_Type            135 non-null    int64
 5   Mobile_Number          135 non-null    object
 6   Gender                 135 non-null    object
 7   DOB                    135 non-null    datetime64[ns]
 8   Premium_Type           135 non-null    object
 9   Date_of_Commencement   135 non-null    datetime64[ns]
 10  End_of_Premium_Paying  135 non-null    datetime64[ns]
 11  Date_of_Maturity       135 non-null    datetime64[ns]
dtypes: datetime64[ns](4), int64(4), object(4)
memory usage: 12.8+ KB

In [39]:
clean_df.to_csv("cleaned_lic_data.csv", index=False)

In [40]:
import os
print(os.getcwd())

C:\Users\sheet\anaconda_projects\158d86d0-2b6b-4eaf-8301-5d7fddcff673

In [1]:
import os
print(os.getcwd())

C:\Users\sheet\anaconda_projects\158d86d0-2b6b-4eaf-8301-5d7fddcff673

In [2]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'cleaned_lic_data.csv', 'Data_LIC(Sheet1) (2).csv', 'import_data.py', 'Untitled.ipynb']

In [3]:
import os
print(os.getcwd())
print(os.listdir())

C:\Users\sheet\anaconda_projects\158d86d0-2b6b-4eaf-8301-5d7fddcff673
['.ipynb_checkpoints', 'cleaned_lic_data.csv', 'Data_LIC(Sheet1) (2).csv', 'import_data.py', 'Untitled.ipynb']

In [1]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFiles:")
print(os.listdir())

Current folder:
C:\Users\sheet\anaconda_projects\LIC projects

Files:
['.ipynb_checkpoints', 'cleaned_lic_data.csv', 'Data_LIC(Sheet1) (2).csv', 'import_data.py', 'Untitled.ipynb']